---

- name: Install PostgreSQL
  homebrew:
      name: postgresql
  notify:
      - Start PostgreSQL

- name: Install Redis
  homebrew:
      name: redis
  notify:
      - Start Redis

- name: Install Couchbase SDK
  homebrew:
      name: libcouchbase
