---

# The Control Strip is the right side of the Touch Bar, normally showing 4 icons.
- name: Change Touch Bar Control Strip
  osx_defaults:
    domain: com.apple.controlstrip
    key: MiniCustomized
    value:
      - com.apple.system.brightness
      - com.apple.system.volume
      - com.apple.system.mute
      - com.apple.system.search
    type: array
  notify:
    - Restart Control Strip

# NOTE: The Ansible osx_defaults module does not yet support a `dict_add` option or a `dict` type, so we have to use the command.
- name: Show function keys in Touch Bar for specific apps, instead of Control Strip and/or per-app controls
  command: defaults write com.apple.touchbar.agent PresentationModePerApp -dict-add "{{ item }}" "functionKeys"
  with_items:
    - com.apple.Terminal
  notify:
    - Restart Touch Bar
