---

- debug:
    msg: Installing software development tools


- name: Install Homebrew version of git, to get new features
  homebrew:
    name: git


- include: atom.yml
  tags: atom
- include: emacs.yml
  tags: emacs
- include: web.yml
  tags: web
- include: postgresql.yml
  tags: [postgresql, postgres]
- include: ruby.yml
  tags: ruby
- include: perl.yml
  tags: perl
- include: java.yml
  tags: java, jdk
- include: node.yml
  tags: node
- include: elm.yml
  tags: elm
- include: racket.yml
  tags: racket
- include: haskell.yml
  tags: haskell
- include: devops.yml
  tags: devops
